In [2]:
%load_ext autoreload
%autoreload 2
import atomic_datasets
import numpy as np
from atomic_datasets import QM9
import pickle
print(atomic_datasets.__file__)

/homefs/home/lawrenh6/datasets/atomic_datasets/__init__.py


In [65]:
DATA_DIR = '/data/lawrenh6'

ds = QM9(root_dir=DATA_DIR, split='train', use_Anderson_splits=True, train_half=None)


In [4]:
len(ds)

Using downloaded data: /data/lawrenh6/gdb9.sdf
Dataset description: QM9 is a comprehensive dataset that provides geometric, energetic, electronic and thermodynamic properties for a subset of GDB-17 database, comprising 134 thousand stable organic molecules with up to 9 heavy atoms. All moleucles are modeled using density functional theory (B3LYP/6-31G(2df,p) based DFT).

The data files:
qm9.sdf: molecular structures
qm9.sdf.csv: tables for molecular properties
	"mol_id" - Molecule ID (gdb9 index) mapping to the .sdf file
	"A" - Rotational constant (unit: GHz)
	"B" - Rotational constant (unit: GHz)
	"C" - Rotational constant (unit: GHz)
	"mu" - Dipole moment (unit: D)
	"alpha" - Isotropic polarizability (unit: Bohr^3)
	"homo" - Highest occupied molecular orbital energy (unit: Hartree)
	"lumo" - Lowest unoccupied molecular orbital energy (unit: Hartree)
	"gap" - Gap between HOMO and LUMO (unit: Hartree)
	"r2" - Electronic spatial extent (unit: Bohr^2)
	"zpve" - Zero point vibrational ene

Loading QM9: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 133885/133885 [00:28<00:00, 4618.82it/s]


Dropping uncharacterized molecules.


487424it [00:00, 927108.26it/s]                                                                                                                                                             


100000

In [5]:
len(ds)

100000

In [66]:
ds_second = QM9(root_dir=DATA_DIR, split='train', use_Anderson_splits=True, train_half='second')
ds_first = QM9(root_dir=DATA_DIR, split='train', use_Anderson_splits=True, train_half='first')

In [67]:
len(ds_first)
len(ds_second)

Using downloaded data: /data/lawrenh6/gdb9.sdf
Dataset description: QM9 is a comprehensive dataset that provides geometric, energetic, electronic and thermodynamic properties for a subset of GDB-17 database, comprising 134 thousand stable organic molecules with up to 9 heavy atoms. All moleucles are modeled using density functional theory (B3LYP/6-31G(2df,p) based DFT).

The data files:
qm9.sdf: molecular structures
qm9.sdf.csv: tables for molecular properties
	"mol_id" - Molecule ID (gdb9 index) mapping to the .sdf file
	"A" - Rotational constant (unit: GHz)
	"B" - Rotational constant (unit: GHz)
	"C" - Rotational constant (unit: GHz)
	"mu" - Dipole moment (unit: D)
	"alpha" - Isotropic polarizability (unit: Bohr^3)
	"homo" - Highest occupied molecular orbital energy (unit: Hartree)
	"lumo" - Lowest unoccupied molecular orbital energy (unit: Hartree)
	"gap" - Gap between HOMO and LUMO (unit: Hartree)
	"r2" - Electronic spatial extent (unit: Bohr^2)
	"zpve" - Zero point vibrational ene

Loading QM9: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 133885/133885 [00:28<00:00, 4774.82it/s]


Dropping uncharacterized molecules.


487424it [00:00, 822638.37it/s]                                                                                                                                                             


train <class 'numpy.ndarray'> [     1      4      5 ... 133881 133883 133884]
saving train half first
train_half_loaded <class 'numpy.ndarray'> [     1      4      5 ... 133881 133883 133884]
Using downloaded data: /data/lawrenh6/gdb9.sdf
Dataset description: QM9 is a comprehensive dataset that provides geometric, energetic, electronic and thermodynamic properties for a subset of GDB-17 database, comprising 134 thousand stable organic molecules with up to 9 heavy atoms. All moleucles are modeled using density functional theory (B3LYP/6-31G(2df,p) based DFT).

The data files:
qm9.sdf: molecular structures
qm9.sdf.csv: tables for molecular properties
	"mol_id" - Molecule ID (gdb9 index) mapping to the .sdf file
	"A" - Rotational constant (unit: GHz)
	"B" - Rotational constant (unit: GHz)
	"C" - Rotational constant (unit: GHz)
	"mu" - Dipole moment (unit: D)
	"alpha" - Isotropic polarizability (unit: Bohr^3)
	"homo" - Highest occupied molecular orbital energy (unit: Hartree)
	"lumo" - Low

Loading QM9: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 133885/133885 [00:28<00:00, 4693.02it/s]


Dropping uncharacterized molecules.


487424it [00:00, 818114.22it/s]                                                                                                                                                             


train <class 'numpy.ndarray'> [     0      3     15 ... 133874 133877 133879]
saving train half second
train_half_loaded <class 'numpy.ndarray'> [     0      3     15 ... 133874 133877 133879]


50000

# look at the inds

In [70]:
with open('/data/lawrenh6/train_half_first.pkl', 'rb') as f:
    first_out = pickle.load(f)
    first_inds = first_out['train']

with open('/data/lawrenh6/train_half_second.pkl', 'rb') as f:
    second_out = pickle.load(f)
    second_inds = second_out['train']

In [77]:
ftpath = "/homefs/home/lawrenh6/e3_diffusion_for_molecules/qm9/temp/qm9/train.npz"
ftout = np.load(ftpath)
print([ky for ky in ftout.keys()])

['num_atoms', 'charges', 'positions', 'index', 'A', 'B', 'C', 'mu', 'alpha', 'homo', 'lumo', 'gap', 'r2', 'zpve', 'U0', 'U', 'H', 'G', 'Cv', 'omega1', 'zpve_thermo', 'U0_thermo', 'U_thermo', 'H_thermo', 'G_thermo', 'Cv_thermo']


In [83]:
ft_num_atoms = [int(na) for na in ftout['num_atoms']]

In [90]:
my_num_atoms = [int(ds_full[i]['n_node']) for i in range(len(ds_full))]

/tmp/ipykernel_256640/553954342.py:1: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  my_num_atoms = [int(ds_full[i]['n_node']) for i in range(len(ds_full))]


In [91]:
len(ft_num_atoms)

100000

In [122]:
np.sort(my_num_atoms) == np.sort(ft_num_atoms) # these aren't sorted either!! 

array([False, False, False, ..., False, False, False], shape=(100000,))

In [93]:
np.sort(ft_num_atoms)

array([ 3,  4,  4, ..., 29, 29, 29], shape=(100000,))

In [88]:
ds_full[0]

{'nodes': {'positions': array([[ 0.1298,  1.5238,  0.048 ],
         [ 0.0214,  0.0349,  0.01  ],
         [-0.1497, -0.6932, -1.1042],
         [-0.2409, -0.1555, -2.3065],
         [-0.2503, -2.0724, -1.1397],
         [-0.1873, -2.7604, -0.1168],
         [-0.0046, -2.1002,  1.1369],
         [ 0.1023, -0.7219,  1.2544],
         [ 0.2619, -0.1682,  2.3823],
         [ 1.082 ,  1.8164,  0.5012],
         [ 0.0515,  1.9512, -0.9516],
         [-0.6542,  1.9377,  0.6896],
         [ 0.2946, -0.8589,  3.1326]]),
  'species': array([1, 1, 1, 4, 2, 2, 3, 1, 2, 0, 0, 0, 0]),
  'atom_types': array(['C', 'C', 'C', 'F', 'N', 'N', 'O', 'C', 'N', 'H', 'H', 'H', 'H'],
        dtype='<U1')},
 'edges': None,
 'receivers': None,
 'senders': None,
 'globals': None,
 'n_node': array([13]),
 'n_edge': None,
 'properties': {'A': 2.35453,
  'B': 1.87611,
  'C': 1.05084,
  'mu': 1.6725,
  'alpha': 66.49,
  'homo': -0.2616,
  'lumo': -0.1004,
  'gap': 0.1612,
  'r2': 1026.4886,
  'zpve': 0.086868,
  'u0'

In [84]:
ds_full = QM9(root_dir=DATA_DIR, split='train', use_Anderson_splits=True, train_half=None)
len(ds_full)

Using downloaded data: /data/lawrenh6/gdb9.sdf
Dataset description: QM9 is a comprehensive dataset that provides geometric, energetic, electronic and thermodynamic properties for a subset of GDB-17 database, comprising 134 thousand stable organic molecules with up to 9 heavy atoms. All moleucles are modeled using density functional theory (B3LYP/6-31G(2df,p) based DFT).

The data files:
qm9.sdf: molecular structures
qm9.sdf.csv: tables for molecular properties
	"mol_id" - Molecule ID (gdb9 index) mapping to the .sdf file
	"A" - Rotational constant (unit: GHz)
	"B" - Rotational constant (unit: GHz)
	"C" - Rotational constant (unit: GHz)
	"mu" - Dipole moment (unit: D)
	"alpha" - Isotropic polarizability (unit: Bohr^3)
	"homo" - Highest occupied molecular orbital energy (unit: Hartree)
	"lumo" - Lowest unoccupied molecular orbital energy (unit: Hartree)
	"gap" - Gap between HOMO and LUMO (unit: Hartree)
	"r2" - Electronic spatial extent (unit: Bohr^2)
	"zpve" - Zero point vibrational ene

Loading QM9: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 133885/133885 [00:30<00:00, 4412.46it/s]


Dropping uncharacterized molecules.


487424it [00:00, 690225.26it/s]                                                                                                                                                             


100000

In [69]:
first_inds

{'train': array([ 70835,  45057, 123404, ..., 103825, 127295,  78745],
       shape=(50000,)),
 'fixed_perm': array([75721, 80184, 19864, ..., 76820,   860, 15795], shape=(100000,))}

In [74]:
out['fixed_perm']

array([75721, 80184, 19864, ..., 76820,   860, 15795], shape=(100000,))

# load inds from where ewa saved them

In [97]:
out.keys()

dict_keys(['sliced_perm', 'dset_train', 'orig_train_dset', 'dset_test', 'fixed_perm', 'len_train'])

In [108]:
second_num_atoms = [int(ds_full[i]['n_node']) for i in range(len(ds_second))]

/tmp/ipykernel_256640/438730073.py:1: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  second_num_atoms = [int(ds_full[i]['n_node']) for i in range(len(ds_second))]


In [111]:

np.sort([int(elt) for elt in out['dset_train']['num_atoms']]) == np.sort(second_num_atoms)

array([False, False, False, ...,  True,  True,  True], shape=(50000,))

In [116]:
orig_num_atoms = [int(elt) for elt in out['orig_train_dset']['num_atoms']]
# no permutation happens in e3 library between preparing dataset / saving and when the permutation is computed



In [123]:
ft_num_atoms

[5,
 4,
 4,
 3,
 4,
 8,
 6,
 7,
 6,
 6,
 11,
 9,
 9,
 7,
 10,
 9,
 8,
 6,
 5,
 4,
 6,
 5,
 10,
 10,
 8,
 8,
 7,
 10,
 9,
 8,
 8,
 14,
 12,
 12,
 10,
 12,
 11,
 10,
 10,
 12,
 10,
 9,
 9,
 8,
 17,
 15,
 8,
 9,
 13,
 12,
 11,
 11,
 10,
 13,
 11,
 12,
 11,
 13,
 12,
 11,
 11,
 10,
 13,
 17,
 15,
 15,
 15,
 13,
 13,
 10,
 11,
 9,
 10,
 9,
 15,
 13,
 13,
 15,
 13,
 14,
 13,
 13,
 9,
 7,
 8,
 8,
 8,
 11,
 12,
 13,
 11,
 10,
 11,
 10,
 13,
 12,
 11,
 11,
 11,
 17,
 15,
 13,
 13,
 10,
 9,
 11,
 10,
 10,
 13,
 13,
 12,
 11,
 13,
 10,
 11,
 15,
 13,
 11,
 11,
 8,
 8,
 8,
 8,
 7,
 7,
 7,
 6,
 6,
 5,
 11,
 15,
 13,
 11,
 5,
 10,
 8,
 13,
 12,
 11,
 11,
 12,
 11,
 10,
 10,
 10,
 10,
 12,
 12,
 11,
 12,
 11,
 10,
 11,
 10,
 13,
 12,
 12,
 11,
 10,
 9,
 16,
 15,
 14,
 13,
 16,
 14,
 18,
 16,
 20,
 18,
 18,
 12,
 11,
 11,
 11,
 10,
 12,
 11,
 11,
 11,
 11,
 11,
 10,
 10,
 16,
 14,
 14,
 16,
 15,
 14,
 14,
 15,
 14,
 15,
 15,
 14,
 14,
 14,
 13,
 13,
 20,
 18,
 18,
 16,
 12,
 11,
 10,
 10,
 16,
 15,
 1

In [117]:
orig_num_atoms

[5,
 4,
 4,
 3,
 4,
 8,
 6,
 7,
 6,
 6,
 11,
 9,
 9,
 7,
 10,
 9,
 8,
 6,
 5,
 4,
 6,
 5,
 10,
 10,
 8,
 8,
 7,
 10,
 9,
 8,
 8,
 14,
 12,
 12,
 10,
 12,
 11,
 10,
 10,
 12,
 10,
 9,
 9,
 8,
 17,
 15,
 8,
 9,
 13,
 12,
 11,
 11,
 10,
 13,
 11,
 12,
 11,
 13,
 12,
 11,
 11,
 10,
 13,
 17,
 15,
 15,
 15,
 13,
 13,
 10,
 11,
 9,
 10,
 9,
 15,
 13,
 13,
 15,
 13,
 14,
 13,
 13,
 9,
 7,
 8,
 8,
 8,
 11,
 12,
 13,
 11,
 10,
 11,
 10,
 13,
 12,
 11,
 11,
 11,
 17,
 15,
 13,
 13,
 10,
 9,
 11,
 10,
 10,
 13,
 13,
 12,
 11,
 13,
 10,
 11,
 15,
 13,
 11,
 11,
 8,
 8,
 8,
 8,
 7,
 7,
 7,
 6,
 6,
 5,
 11,
 15,
 13,
 11,
 5,
 10,
 8,
 13,
 12,
 11,
 11,
 12,
 11,
 10,
 10,
 10,
 10,
 12,
 12,
 11,
 12,
 11,
 10,
 11,
 10,
 13,
 12,
 12,
 11,
 10,
 9,
 16,
 15,
 14,
 13,
 16,
 14,
 18,
 16,
 20,
 18,
 18,
 12,
 11,
 11,
 11,
 10,
 12,
 11,
 11,
 11,
 11,
 11,
 10,
 10,
 16,
 14,
 14,
 16,
 15,
 14,
 14,
 15,
 14,
 15,
 15,
 14,
 14,
 14,
 13,
 13,
 20,
 18,
 18,
 16,
 12,
 11,
 10,
 10,
 16,
 15,
 1

In [118]:
my_num_atoms

[13,
 17,
 17,
 12,
 14,
 15,
 16,
 17,
 19,
 21,
 19,
 16,
 21,
 17,
 25,
 19,
 18,
 19,
 20,
 15,
 19,
 19,
 18,
 18,
 19,
 21,
 18,
 14,
 21,
 23,
 23,
 11,
 13,
 18,
 15,
 18,
 21,
 16,
 19,
 15,
 12,
 19,
 13,
 21,
 19,
 20,
 21,
 19,
 18,
 21,
 21,
 18,
 18,
 20,
 12,
 20,
 17,
 16,
 14,
 15,
 18,
 21,
 21,
 19,
 19,
 18,
 20,
 19,
 15,
 16,
 18,
 17,
 17,
 19,
 16,
 25,
 19,
 14,
 19,
 17,
 17,
 19,
 18,
 18,
 23,
 20,
 19,
 15,
 15,
 17,
 20,
 18,
 21,
 21,
 20,
 16,
 21,
 18,
 12,
 15,
 23,
 15,
 20,
 19,
 19,
 19,
 17,
 17,
 23,
 19,
 16,
 19,
 15,
 14,
 20,
 15,
 17,
 16,
 20,
 11,
 17,
 16,
 25,
 11,
 21,
 15,
 17,
 21,
 19,
 17,
 15,
 19,
 20,
 18,
 23,
 19,
 19,
 14,
 20,
 15,
 22,
 16,
 20,
 18,
 15,
 21,
 18,
 17,
 15,
 23,
 18,
 16,
 23,
 21,
 12,
 15,
 21,
 19,
 23,
 13,
 21,
 16,
 19,
 18,
 18,
 20,
 19,
 18,
 23,
 14,
 14,
 14,
 19,
 15,
 16,
 17,
 19,
 16,
 18,
 14,
 14,
 21,
 20,
 20,
 20,
 17,
 22,
 20,
 19,
 18,
 15,
 24,
 18,
 15,
 14,
 21,
 23,
 18,
 12,
 18,


In [121]:
np.mean(np.sort([int(elt) for elt in out['orig_train_dset']['num_atoms']]) == np.sort(my_num_atoms))

np.float64(1.0)

In [ ]:
# this means: orig_train_dset is permuted relative to my_num_atoms


In [114]:
my_num_atoms

[13,
 17,
 17,
 12,
 14,
 15,
 16,
 17,
 19,
 21,
 19,
 16,
 21,
 17,
 25,
 19,
 18,
 19,
 20,
 15,
 19,
 19,
 18,
 18,
 19,
 21,
 18,
 14,
 21,
 23,
 23,
 11,
 13,
 18,
 15,
 18,
 21,
 16,
 19,
 15,
 12,
 19,
 13,
 21,
 19,
 20,
 21,
 19,
 18,
 21,
 21,
 18,
 18,
 20,
 12,
 20,
 17,
 16,
 14,
 15,
 18,
 21,
 21,
 19,
 19,
 18,
 20,
 19,
 15,
 16,
 18,
 17,
 17,
 19,
 16,
 25,
 19,
 14,
 19,
 17,
 17,
 19,
 18,
 18,
 23,
 20,
 19,
 15,
 15,
 17,
 20,
 18,
 21,
 21,
 20,
 16,
 21,
 18,
 12,
 15,
 23,
 15,
 20,
 19,
 19,
 19,
 17,
 17,
 23,
 19,
 16,
 19,
 15,
 14,
 20,
 15,
 17,
 16,
 20,
 11,
 17,
 16,
 25,
 11,
 21,
 15,
 17,
 21,
 19,
 17,
 15,
 19,
 20,
 18,
 23,
 19,
 19,
 14,
 20,
 15,
 22,
 16,
 20,
 18,
 15,
 21,
 18,
 17,
 15,
 23,
 18,
 16,
 23,
 21,
 12,
 15,
 21,
 19,
 23,
 13,
 21,
 16,
 19,
 18,
 18,
 20,
 19,
 18,
 23,
 14,
 14,
 14,
 19,
 15,
 16,
 17,
 19,
 16,
 18,
 14,
 14,
 21,
 20,
 20,
 20,
 17,
 22,
 20,
 19,
 18,
 15,
 24,
 18,
 15,
 14,
 21,
 23,
 18,
 12,
 18,


In [6]:
first_half_ewa_file = '/data/bucket/guided_generation_SM/datasets/qm9/qm9_first_half/train.npz'
second_half_ewa_file = '/data/bucket/guided_generation_SM/datasets/qm9/qm9_second_half/train.npz'

In [7]:
first_ewa = np.load(first_half_ewa_file)
second_ewa = np.load(second_half_ewa_file)

In [8]:
[first_ewa[ky] == second_ewa[ky] for ky in first_ewa.keys()]

[array([ True,  True,  True, ...,  True,  True,  True], shape=(100000,)),
 array([[ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        ...,
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True]],
       shape=(100000, 29)),
 array([[[ True,  True,  True],
         [ True,  True,  True],
         [ True,  True,  True],
         ...,
         [ True,  True,  True],
         [ True,  True,  True],
         [ True,  True,  True]],
 
        [[ True,  True,  True],
         [ True,  True,  True],
         [ True,  True,  True],
         ...,
         [ True,  True,  True],
         [ True,  True,  True],
         [ True,  True,  True]],
 
        [[ True,  True,  True],
         [ True,  True,  True],
         [ True,  True,  True],
         ...,
         [ Tru

In [9]:
print([key for key in first_ewa.keys()])

['num_atoms', 'charges', 'positions', 'index', 'A', 'B', 'C', 'mu', 'alpha', 'homo', 'lumo', 'gap', 'r2', 'zpve', 'U0', 'U', 'H', 'G', 'Cv', 'omega1', 'zpve_thermo', 'U0_thermo', 'U_thermo', 'H_thermo', 'G_thermo', 'Cv_thermo']


# compare indices

In [10]:
np.sort(first_ewa['index'])

array([     1,      2,      4, ..., 133882, 133884, 133885],
      shape=(100000,))

In [11]:
np.sort(first_inds)

array([     1,      4,      5, ..., 133881, 133883, 133884],
      shape=(50000,))

In [12]:
np.sort(second_ewa['index'])

array([     1,      2,      4, ..., 133882, 133884, 133885],
      shape=(100000,))

In [13]:
np.sort(second_inds)

array([     0,      3,     15, ..., 133874, 133877, 133879],
      shape=(50000,))

In [14]:
set(first_ewa['index'])

{np.int64(1),
 np.int64(2),
 np.int64(4),
 np.int64(5),
 np.int64(6),
 np.int64(7),
 np.int64(8),
 np.int64(9),
 np.int64(10),
 np.int64(12),
 np.int64(13),
 np.int64(15),
 np.int64(16),
 np.int64(17),
 np.int64(18),
 np.int64(19),
 np.int64(20),
 np.int64(23),
 np.int64(24),
 np.int64(25),
 np.int64(26),
 np.int64(27),
 np.int64(29),
 np.int64(30),
 np.int64(32),
 np.int64(33),
 np.int64(34),
 np.int64(35),
 np.int64(36),
 np.int64(37),
 np.int64(38),
 np.int64(39),
 np.int64(40),
 np.int64(41),
 np.int64(42),
 np.int64(43),
 np.int64(45),
 np.int64(46),
 np.int64(48),
 np.int64(49),
 np.int64(50),
 np.int64(51),
 np.int64(52),
 np.int64(53),
 np.int64(54),
 np.int64(55),
 np.int64(57),
 np.int64(60),
 np.int64(63),
 np.int64(64),
 np.int64(65),
 np.int64(66),
 np.int64(67),
 np.int64(68),
 np.int64(69),
 np.int64(70),
 np.int64(71),
 np.int64(72),
 np.int64(73),
 np.int64(75),
 np.int64(77),
 np.int64(79),
 np.int64(82),
 np.int64(83),
 np.int64(84),
 np.int64(85),
 np.int64(86),
 np

In [15]:
import heapq
ewa_merged = set(heapq.merge(list(first_ewa['index']), list(second_ewa['index'])))
print(f'len of first \n {len(first_ewa['index'])} len of second {len(second_ewa['index'])} \n len of merged {len(ewa_merged)}')


len of first 
 100000 len of second 100000 
 len of merged 100000


In [16]:
my_merged = set(heapq.merge(list(first_inds), list(second_inds)))

In [17]:
len(my_merged)

100000

In [18]:
my_merged = [int(i) for i in my_merged]
ewa_merged = [int(i) for i in ewa_merged]

In [19]:
np.sort(my_merged)

array([     0,      1,      3, ..., 133881, 133883, 133884],
      shape=(100000,))

In [20]:
np.sort(ewa_merged)

array([     1,      2,      4, ..., 133882, 133884, 133885],
      shape=(100000,))

In [72]:
second_edm_file = '/homefs/home/lawrenh6/e3_diffusion_for_molecules/sliced_perm_edm_qm9_second_half.pkl'
with open(second_edm_file, 'rb') as f:
    out = pickle.load(f)

In [61]:
out.keys()

dict_keys(['sliced_perm', 'dset_train', 'orig_train_dset', 'dset_test', 'fixed_perm', 'len_train'])

In [73]:
out['fixed_perm']

array([75721, 80184, 19864, ..., 76820,   860, 15795], shape=(100000,))

In [63]:
out['len_train']

100000

In [25]:
np.sort(out['sliced_perm'])

array([    0,     1,     2, ..., 99995, 99997, 99998], shape=(50000,))

In [26]:
len(np.sort(out['sliced_perm']))

50000

In [30]:
sorted_second_from_e3 = np.sort(out['sliced_perm'])
print([int(sorted_second_from_e3[i]) for i in range(50)])

[0, 1, 2, 3, 5, 9, 10, 11, 13, 14, 15, 16, 17, 18, 19, 20, 22, 25, 26, 28, 29, 30, 31, 36, 37, 38, 42, 43, 44, 45, 46, 47, 48, 50, 51, 55, 56, 57, 58, 59, 60, 61, 63, 64, 65, 66, 67, 68, 71, 74]


In [31]:
np.sort(second_inds)

array([     0,      3,     15, ..., 133874, 133877, 133879],
      shape=(50000,))

In [32]:
sorted_second_from_e3

array([    0,     1,     2, ..., 99995, 99997, 99998], shape=(50000,))

In [34]:
out['dset_train']['num_atoms']

tensor([22, 23, 18,  ..., 22, 13, 13])

In [36]:
ds_second = QM9(root_dir='/data/lawrenh6', split='train', use_Anderson_splits=True, train_half='second')

In [52]:
my_atoms = np.sort([ds_second[i]['n_node'] for i in range(len(ds_second))])
my_atoms = np.sort(my_atoms[:,0])

In [46]:
edm_atoms = np.sort(out['dset_train']['num_atoms'])

In [53]:
my_atoms == edm_atoms

array([False,  True, False, ...,  True,  True,  True], shape=(50000,))

In [54]:
print(my_atoms[:100])

[4 4 5 5 6 6 6 6 6 6 7 7 7 7 7 7 7 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8
 8 8 8 8 8 8 8 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9
 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9]


In [55]:
print(edm_atoms[:100])

[3 4 4 4 5 5 5 6 6 6 6 6 7 7 7 7 7 7 7 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8
 8 8 8 8 8 8 8 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9
 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9]
